/*
 BSD 3-Clause License
 
 Copyright (c) 2019, Udaybhaskar Sarma Seetamraju
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
 * Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 
 * Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 
 * Neither the name of the copyright holder nor the names of its
 contributors may be used to endorse or promote products derived from
 this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.ASUX.YAML.NodeImpl;

import org.ASUX.common.Tuple;
import org.ASUX.common.Output;

import org.ASUX.yaml.YAML_Libraries;

import java.util.LinkedList;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Properties;

// https://yaml.org/spec/1.2/spec.html#id2762107
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.composer.Composer;
import org.yaml.snakeyaml.nodes.NodeTuple;
import org.yaml.snakeyaml.nodes.NodeId;
import org.yaml.snakeyaml.nodes.Node;
import org.yaml.snakeyaml.nodes.ScalarNode;
import org.yaml.snakeyaml.nodes.MappingNode;
import org.yaml.snakeyaml.nodes.SequenceNode;
import org.yaml.snakeyaml.constructor.Constructor;
import org.yaml.snakeyaml.error.Mark; // https://bitbucket.org/asomov/snakeyaml/src/default/src/main/java/org/yaml/snakeyaml/error/Mark.java
import org.yaml.snakeyaml.DumperOptions;

import static org.junit.Assert.*;

/**
 *  <p>This class is a bunch of tools to help make it easy to work with the java.util.Map objects that the YAML library creates.</p>
 *  <p>One example is the work around required when replacing the 'Key' - within the MACRO command Processor.</p>
 *  <p>If the key is already inside single or double-quotes.. then the replacement ends up as <code>'"newkeystring"'</code></p>
 */
public class Tools extends org.ASUX.yaml.Tools {

    public static final String CLASSNAME = Tools.class.getName();
    private CmdInvoker cmdInvoker;

    //==============================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //==============================================================================

    /**
      * <p>Utility class for use within the org.ASUX.yaml library only</p><p>one of 2 constructors - public/private/protected</p>
      * @param _verbose Whether you want deluge of debug-output onto System.out.
      */
    public Tools(boolean _verbose ) {
        super( _verbose );
    }

    //==============================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //==============================================================================

    /**
     * Allows this class to get the YAML-Library specific implementation details from the appropriate subclass of CmdInvoker
     * @param _cmdInvoker instance of org.ASUX.yaml.CmdInvoker - specifically its subclasses org.ASUX.yaml.CollectionsImpl.CmdInvoker / org.ASUX.yaml.NodeImpl.CmdInvoker
     */
    public void setCmdInvoker( final org.ASUX.yaml.CmdInvoker _cmdInvoker ) {
        this.cmdInvoker = (CmdInvoker)_cmdInvoker;// I know what I'm doing...
        // This Tools class and cmdInvoker should belong in the SAME PACKAGE.
    }


    //==============================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //==============================================================================

    /** Takes any YAML input - as a LinkedHashmap - and exports it as YAML-String (to java.util.String)
     *  @param _yaml a java.util.LinkedHashMap&lt;String, Object&gt; object, as generated by Jackson http://tutorials.jenkov.com/java-json/jackson-objectmapper.html#read-map-from-json-string 
     *  @return a java.util.LinkedHashMap&lt;String, Object&gt; object that's definitely "kosher" for the entire org.ASUX.yaml library to work without any issues
     *  @throws Exception Any issue whatsoever when dealing with convering YAML/JSON content into Strings and back (as part of lintremoval)
     */
    public String Map2YAMLString( final LinkedHashMap<String, Object> _yaml ) throws Exception
    {
        final java.io.StringWriter strwrtr3 = new java.io.StringWriter();
        try {
            this.cmdInvoker.getYamlWriter().prepare( strwrtr3 );
            this.cmdInvoker.getYamlWriter().write( _yaml );
            this.cmdInvoker.getYamlWriter().close();
            if ( this.verbose ) System.out.println( CLASSNAME + ": Map2YAMLString(): created new YAML-String\n" + strwrtr3.toString() +"\n" );

            return strwrtr3.toString();

        } catch (java.io.IOException e) {
            if ( this.verbose ) e.printStackTrace(System.err);
            if ( this.verbose ) System.err.println( CLASSNAME + ": Map2YAMLString(): Failure to read/write the contents of the String '" + strwrtr3.toString() +"'.");
            throw e;
        } catch (Exception e) {
            if ( this.verbose ) e.printStackTrace(System.err);
            if ( this.verbose ) System.err.println( CLASSNAME + ": Map2YAMLString(): Unknown Internal error:.");
            throw e;
        }
        // return null;
    } // function

    //==============================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //==============================================================================

    /**
     *  Takes any STRING-form JSON as input - it better be valid JSON - and reads it back as YAML/LinkedHashMap.
     *  I need such a function, as I learned the hard way that libraries do NOT work 100% well.  Only file-formats are the workaorund/ way out.
     *  I definitely "fgool-proof" method to ensure 'valid' YAML, for error-free processing by the entire org.ASUX.yaml library to work without any issues
     *  @param _yamlString a java.lang.String object
     *  @param _bWrapScalar true or false.  If the returne value is going to be a SCALAR, do you want it wrapped into a LinkedHashMap or throw instead?
     *  @return a java.util.LinkedHashMap&lt;String, Object&gt; object that's definitely "kosher" for the entire org.ASUX.yaml library to work without any issues
     * @throws java.io.IOException if any error using java.io.StringReader and java.io.StringWriter
     * @throws Exception any other run-time exception, while parsing large Strings, nullpointers, etc.. ..
     */
    public LinkedHashMap<String, Object>  YAMLString2Map( final String  _yamlString, final boolean _bWrapScalar )
                    throws java.io.IOException, Exception
    {
        if ( this.verbose ) System.out.println(">>>>>>>>>>>>>>>>>>>> "+ CLASSNAME+": YAMLString2Map(): "+ _yamlString);

        try {
            final java.io.Reader reader3 = new java.io.StringReader( _yamlString );
            final Node outpObj = this.cmdInvoker.getYamlScanner().load( reader3 );
            reader3.close();
            if ( this.verbose ) System.out.println( CLASSNAME + ": YAMLString2Map(): created new Map = " + outpObj +" " );

            return this.Node2Map( outpObj ).getMap();

        } catch (Exception e) {
            // YamlReader$YamlReaderException: Line 0, column 10: Expected data for a java.util.LinkedHashMap field but found: scalar
            if (this.verbose) System.out.println( CLASSNAME+": YAMLString2Map(): Hmmm.. Just a string?? passed as parameter??");
            // if ( e.getMessage().contains("Expected data for a java.util.LinkedHashMap field but found: scalar"))
            if ( e.getMessage().contains("but found: scalar") && _bWrapScalar )
                return new Output(this.verbose).wrapAnObject_intoLinkedHashMap( _yamlString );
            else {
                if ( this.verbose ) e.printStackTrace(System.err);
                if ( this.verbose ) System.err.println( CLASSNAME+": YAMLString2Map(): Input String ["+ _yamlString +"] does Not seem to be YAML - nor - a simple SCALAR string" );
                throw e;
            }
        }
    } // function

    //=================================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //=================================================================================

    /** Takes any YAML input - as a LinkedHashmap - and exports it as org.yaml.snakeyaml.nodes.Node (compliant with SnakeYAML library)
     *  @param _yaml a java.util.LinkedHashMap&lt;String, Object&gt; object, as generated by Jackson http://tutorials.jenkov.com/java-json/jackson-objectmapper.html#read-map-from-json-string 
     *  @return a java.util.LinkedHashMap&lt;String, Object&gt; object that's definitely "kosher" for the entire org.ASUX.yaml library to work without any issues
     *  @throws Exception Any issue whatsoever when dealing with convering YAML/JSON content into Strings and back (as part of lintremoval)
     */
    public org.yaml.snakeyaml.nodes.Node Map2Node( final LinkedHashMap<String, Object> _yaml ) throws Exception
    {
        final String es = CLASSNAME + ": Map2Node(): Unimplemented method of org.ASUX.YAML.NodeImpl (SnakeYAML-based) Library .. Needed by NodeImpl.CmdInvoker.getDataFromReference() for converting JSON files provided via cmdline @method?";
        System.err.println( es );
        throw new Exception( es );
    }

    //=================================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //=================================================================================

    /**
     * Takes a org.yaml.snakeyaml.nodes.Node object and converts it into a LinkedHashMap heirarchy that is compatible with ESO TERIC SOFT WARE'S YAML LIBRARY
     * @param args an instance of org.yaml.snakeyaml.nodes.Node
     * @return instance of {@link org.ASUX.common.Output.Object} which will contain the appropriate object.
     * @throws Exception if any invalid Node object hierarchy, or if unimplemented scenarios.
     */
    public org.ASUX.common.Output.Object<?> Node2Map( final Node _node ) throws Exception
    {
        org.ASUX.common.Output.Object<?> outputObj= null;

        // public enum org.yaml.snakeyaml.nodes.NodeId = scalar, sequence, mapping, anchor
        final NodeId nid = _node.getNodeId(); // https://bitbucket.org/asomov/snakeyaml/src/default/src/main/java/org/yaml/snakeyaml/nodes/NodeId.java
        if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): @top, node-id = ["+ nid + "]" );

        if ( _node instanceof MappingNode ) {
            // https://yaml.org/spec/1.2/spec.html#id2762107
            // https://bitbucket.org/asomov/snakeyaml/src/default/src/main/java/org/yaml/snakeyaml/nodes/MappingNode.java   
            final MappingNode map = (MappingNode) _node;
            // MappingNode(Tag ignore, boolean resolved, List<NodeTuple> value, Mark startMark, Mark endMark, DumperOptions.FlowStyle flowStyle)
            final java.util.List<NodeTuple> tuples = map.getValue();
            // https://bitbucket.org/asomov/snakeyaml/src/default/src/main/java/org/yaml/snakeyaml/nodes/NodeTuple.java
            if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): Mapping-node has value/tuples= ["+ tuples + "]" );

            final LinkedHashMap<String, Object> lhm = new LinkedHashMap<String, Object>();
            for( NodeTuple kv: tuples ) {
                final Node key = kv.getKeyNode();
                assert ( key.getNodeId() == NodeId.scalar ); // if assert fails, what scenario does that represent?
                final ScalarNode scalarKey = (ScalarNode) key;
                String kstr = (scalarKey.getTag().startsWith("!")) ? (scalarKey.getTag()+" ") : "";
                kstr += scalarKey.getValue();

                final Node val = kv.getValueNode();
                if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): found LHS: RHS = ["+ key + "] : ["+ val + "]" );

                if ( val.getNodeId() == NodeId.scalar) {
                    final ScalarNode scalarVal = (ScalarNode) val;
                    String v = (scalarVal.getTag().startsWith("!")) ? (scalarVal.getTag()+" ") : "";
                    v += scalarVal.getValue();
                    lhm.put( kstr, v );
                    if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): >>>>>>>>>>> ADDED SCALAR KV-pair= ["+ kstr + "] = ["+ v + "]" );

                } else {
                    if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): recursing.. ..= ["+ val.getNodeId() + "]" );
                    final org.ASUX.common.Output.Object<?> asuxobj = Node2Map( val );
                    lhm.put( kstr, asuxobj.getJavaObject() );
                }
            } // for
            if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): function-returning a LinkedHashMap = ["+ lhm + "]" );
            outputObj = new org.ASUX.common.Output.Object<String>();
            outputObj.setMap( lhm );
            return outputObj;

        } else if ( _node instanceof SequenceNode ) {
            // https://bitbucket.org/asomov/snakeyaml/src/default/src/main/java/org/yaml/snakeyaml/nodes/SequenceNode.java
            final SequenceNode seq = (SequenceNode) _node;
            // SequenceNode(Tag ignore, boolean resolved, List<Node> value, Mark startMark, Mark endMark, DumperOptions.FlowStyle flowStyle)
            if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): SEQUENCE-node-id = ["+ seq.getNodeId() + "]" );

            final java.util.List<Node> lst = seq.getValue();
            final ArrayList<Object> arrObj = new ArrayList<Object>();
            final ArrayList<String> arrStr = new ArrayList<String>();
            boolean bNonScalarsDetected = false;
            for( Node val: lst ) {
                if ( val.getNodeId() == NodeId.scalar) {
                    final ScalarNode scalarVal = (ScalarNode) val;
                    String v = (scalarVal.getTag().startsWith("!")) ? (scalarVal.getTag()+" ") : "";
                    v += scalarVal.getValue();
                    arrObj.add( v );
                    arrStr.add( v );
                    if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): >>>>>>>>>>> ADDED SCALAR into Array = ["+ scalarVal.getValue() + "]" );
                } else {
                    if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): recursing.. ..= ["+ val.getNodeId() + "]" );
                    final org.ASUX.common.Output.Object<?> asuxobj = Node2Map( val );
                    arrObj.add( asuxobj.getJavaObject() );
                    bNonScalarsDetected = true;
                }
            } // for
            if ( bNonScalarsDetected ) {
                final org.ASUX.common.Output.Object<java.lang.Object> o2 = new org.ASUX.common.Output.Object<java.lang.Object>();
                o2.setArray( arrObj );
                outputObj = o2;
            } else {
                final org.ASUX.common.Output.Object<String> o3 = new org.ASUX.common.Output.Object<String>();
                o3.setArray( arrStr );
                outputObj = o3;
            }
            if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): function-returning something = ["+ outputObj + "]" );
            return outputObj;

        } else if ( _node instanceof ScalarNode ) {
            // https://bitbucket.org/asomov/snakeyaml/src/default/src/main/java/org/yaml/snakeyaml/nodes/ScalarNode.java
            final ScalarNode scalarVal = (ScalarNode) _node;
            // ScalarNode(Tag ignore, String value, Mark startMark, Mark endMark, DumperOptions.ScalarStyle style)
            String v = (scalarVal.getTag().startsWith("!")) ? (scalarVal.getTag()+" ") : "";
            v += scalarVal.getValue();
            // boolean scalarVal.isPlain()
            // lhm.put( ??What-is-the-Key??? , val );
            if ( this.verbose ) System.out.println( CLASSNAME +" Node2Map(): >>>>>>>>>>> returning a SCALAR !! = ["+ v + "]" );
            final org.ASUX.common.Output.Object<String> o4 = new org.ASUX.common.Output.Object<String>();
            o4.setString( v );
            return o4;

        } else {
            final String erms = CLASSNAME + ": main(): Unimplemented SnakeYaml Node-type: " + nid +" = ["+ _node.toString() +"]";
            System.err.println( erms );
            throw new Exception( erms );
        } // if-else-if-else
    } // function

    //==============================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //==============================================================================

    public static Node getNewSingleNode( final Node _orig ) {
        switch ( _orig.getNodeId() ) {
            case scalar: 
                // final ScalarNode newNode = new ScalarNode( keytagNM, keyNM, scalarKey.getStartMark(), scalarKey.getEndMark(), scalarKey.getScalarStyle() );
                // ScalarNode(Tag tag, String value, Mark startMark, Mark endMark, DumperOptions.ScalarStyle style)
            case sequence:
            case mapping:
            case anchor:
        }
        return null;
    }
    //==============================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //==============================================================================

    //==============================================================================
    //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //==============================================================================

    public static void main( String[] args ) {
        try {
            final GenericYAMLScanner rdr = new GenericYAMLScanner(true);
            rdr.setYamlLibrary( YAML_Libraries.ESOTERICSOFTWARE_Library );
            final GenericYAMLWriter wr = new GenericYAMLWriter(true);
            wr.setYamlLibrary( YAML_Libraries.ESOTERICSOFTWARE_Library );
            final Tools tools = new Tools( true );
            // tools.cmdInvoker
            // LinkedHashMap<String, Object> map = tools.JSONString2Node????????????????????????????????????????????( args[0] );
            // System.out.println("Normal completion of program");
        // } catch (java.io.IOException e) {
        //     e.printStackTrace(System.err);
        //     System.exit(102);
        } catch (Exception e) {
            if ( e.getMessage().contains("but found: scalar" ) ) {
                System.out.println("\n\n Just a string!" );
            } else {
                e.printStackTrace(System.err);
                System.exit(103);
            }
        }
        System.exit(0);
    }

}
